"""create accounts table

Revision ID: 25d488cb0e11
Revises: 76154104a7c7
Create Date: 2026-08-19 12:50:12.655856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d488cb0e11'
down_revision: Union[str, None] = '76154104a7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['platform.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_accounts_email'), 'accounts', ['email'], unique=True, schema='platform')
    op.create_index(op.f('ix_platform_accounts_organization_id'), 'accounts', ['organization_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_accounts_role'), 'accounts', ['role'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_accounts_role'), table_name='accounts', schema='platform')
    op.drop_index(op.f('ix_platform_accounts_organization_id'), table_name='accounts', schema='platform')
    op.drop_index(op.f('ix_platform_accounts_email'), table_name='accounts', schema='platform')
    op.drop_table('accounts', schema='platform')
    # ### end Alembic commands ###
