"""create events table

Revision ID: 3bc58ea2b272
Revises: a63727f90ee0
Create Date: 2026-08-18 15:06:51.355165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc58ea2b272'
down_revision: Union[str, None] = 'a63727f90ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('condition_id', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['platform.cameras.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['platform.modules.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['platform.zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_events_camera_id'), 'events', ['camera_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_events_event_type'), 'events', ['event_type'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_events_module_id'), 'events', ['module_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_events_occurred_at'), 'events', ['occurred_at'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_events_zone_id'), 'events', ['zone_id'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_events_zone_id'), table_name='events', schema='platform')
    op.drop_index(op.f('ix_platform_events_occurred_at'), table_name='events', schema='platform')
    op.drop_index(op.f('ix_platform_events_module_id'), table_name='events', schema='platform')
    op.drop_index(op.f('ix_platform_events_event_type'), table_name='events', schema='platform')
    op.drop_index(op.f('ix_platform_events_camera_id'), table_name='events', schema='platform')
    op.drop_table('events', schema='platform')
    # ### end Alembic commands ###
