"""add account resource access

Revision ID: 3e711ced1d6f
Revises: 25d488cb0e11
Create Date: 2026-08-20 13:10:27.601890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e711ced1d6f'
down_revision: Union[str, None] = '25d488cb0e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_site_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform.accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['platform.sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'site_id', name='uq_account_site_access_account_site'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_account_site_access_account_id'), 'account_site_access', ['account_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_account_site_access_site_id'), 'account_site_access', ['site_id'], unique=False, schema='platform')
    op.create_table('account_camera_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform.accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['camera_id'], ['platform.cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'camera_id', name='uq_account_camera_access_account_camera'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_account_camera_access_account_id'), 'account_camera_access', ['account_id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_account_camera_access_camera_id'), 'account_camera_access', ['camera_id'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_account_camera_access_camera_id'), table_name='account_camera_access', schema='platform')
    op.drop_index(op.f('ix_platform_account_camera_access_account_id'), table_name='account_camera_access', schema='platform')
    op.drop_table('account_camera_access', schema='platform')
    op.drop_index(op.f('ix_platform_account_site_access_site_id'), table_name='account_site_access', schema='platform')
    op.drop_index(op.f('ix_platform_account_site_access_account_id'), table_name='account_site_access', schema='platform')
    op.drop_table('account_site_access', schema='platform')
    # ### end Alembic commands ###
