"""create event evidence table

Revision ID: 76154104a7c7
Revises: 3bc58ea2b272
Create Date: 2026-08-18 16:48:39.993377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76154104a7c7'
down_revision: Union[str, None] = '3bc58ea2b272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['platform.events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_event_evidence_event_id'), 'event_evidence', ['event_id'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_event_evidence_event_id'), table_name='event_evidence', schema='platform')
    op.drop_table('event_evidence', schema='platform')
    # ### end Alembic commands ###
