"""
AI Detection Schemas

Handles AI model detection results from cameras.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional
from uuid import UUID

from pydantic import Field

from app.schemas.base import BaseResponseSchema, BaseSchema


# ==========================================================
# Base
# ==========================================================

class DetectionBase(BaseSchema):
    """
    Common detection fields.
    """

    camera_id: UUID

    ai_model_id: Optional[UUID] = None

    detection_type: str = Field(
        ...,
        min_length=2,
        max_length=100,
        examples=[
            "face",
            "helmet",
            "fire",
            "vehicle",
            "person"
        ]
    )

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0
    )

    label: str = Field(
        ...,
        max_length=100
    )

    frame_number: Optional[int] = None

    timestamp: datetime


# ==========================================================
# Create Detection
# ==========================================================

class DetectionCreate(DetectionBase):
    """
    Detection generated by AI engine.
    """

    bounding_box: Optional[Dict[str, float]] = None

    metadata: Optional[Dict[str, Any]] = None


# ==========================================================
# Update Detection
# ==========================================================

class DetectionUpdate(BaseSchema):
    """
    Update detection status.
    """

    is_processed: Optional[bool] = None

    metadata: Optional[Dict[str, Any]] = None


# ==========================================================
# Response
# ==========================================================

class DetectionResponse(BaseResponseSchema):
    """
    Detection response.
    """

    camera_id: UUID

    ai_model_id: Optional[UUID]

    detection_type: str

    label: str

    confidence: float

    frame_number: Optional[int]

    timestamp: datetime

    bounding_box: Optional[Dict[str, float]]

    metadata: Optional[Dict[str, Any]]

    is_processed: bool


# ==========================================================
# Detection Detail
# ==========================================================

class DetectionDetailResponse(DetectionResponse):
    """
    Detailed detection information.
    """

    camera_name: Optional[str] = None

    model_name: Optional[str] = None

    organization_name: Optional[str] = None


# ==========================================================
# List Response
# ==========================================================

class DetectionListResponse(BaseSchema):
    """
    Paginated detection list.
    """

    detections: list[DetectionResponse]

    total: int

    page: int

    page_size: int


# ==========================================================
# Filter
# ==========================================================

class DetectionFilter(BaseSchema):
    """
    Detection search filters.
    """

    camera_id: Optional[UUID] = None

    ai_model_id: Optional[UUID] = None

    detection_type: Optional[str] = None

    label: Optional[str] = None

    min_confidence: Optional[float] = Field(
        default=None,
        ge=0,
        le=1
    )

    max_confidence: Optional[float] = Field(
        default=None,
        ge=0,
        le=1
    )

    start_date: Optional[datetime] = None

    end_date: Optional[datetime] = None

    page: int = 1

    page_size: int = 20


# ==========================================================
# Statistics
# ==========================================================

class DetectionStatistics(BaseSchema):
    """
    AI analytics summary.
    """

    total_detections: int = 0

    average_confidence: float = 0.0

    highest_confidence: float = 0.0

    detection_types: Dict[str, int] = {}


# ==========================================================
# Delete Response
# ==========================================================

class DetectionDeleteResponse(BaseSchema):

    success: bool = True

    message: str = "Detection deleted successfully."