"""add detection_enabled to cameras

Revision ID: 2fa960858f8c
Revises: 44baaf49d0e6
Create Date: 2026-08-05 16:55:28.050111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa960858f8c'
down_revision: Union[str, None] = '44baaf49d0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
