"""add detection enabled and camera code

Revision ID: 44baaf49d0e6
Revises: 1b22bc5175ca
Create Date: 2026-08-05 16:25:55.053350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44baaf49d0e6'
down_revision: Union[str, None] = '1b22bc5175ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('detection_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'detection_enabled')
    # ### end Alembic commands ###
