"""add code to permissions

Revision ID: 8f5d1905a89a
Revises: 
Create Date: 2026-08-05 15:06:50.748018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5d1905a89a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('code', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_column('permissions', 'code')
    # ### end Alembic commands ###
