"""
Notification Model

Stores user notifications generated by
alerts, events, reports and system actions.
"""

from sqlalchemy import (
    Column,
    String,
    Boolean,
    Text,
    ForeignKey,
    Enum,
)

from sqlalchemy.orm import relationship

from app.models.base import BaseModel

import enum


class NotificationType(str, enum.Enum):
    ALERT = "alert"
    SYSTEM = "system"
    REPORT = "report"
    SECURITY = "security"


class Notification(BaseModel):
    __tablename__ = "notifications"


    # =====================================================
    # Foreign Keys
    # =====================================================

    user_id = Column(
        String,
        ForeignKey(
            "users.id",
            ondelete="CASCADE"
        ),
        nullable=False
    )


    organization_id = Column(
        String,
        ForeignKey(
            "organizations.id",
            ondelete="CASCADE"
        ),
        nullable=False
    )


    # =====================================================
    # Notification Data
    # =====================================================

    title = Column(
        String(255),
        nullable=False
    )


    message = Column(
        Text,
        nullable=False
    )


    notification_type = Column(
        Enum(NotificationType),
        default=NotificationType.SYSTEM
    )


    is_read = Column(
        Boolean,
        default=False
    )


    # =====================================================
    # Relationships
    # =====================================================

    user = relationship(
        "User",
        back_populates="notifications"
    )


    organization = relationship(
        "Organization"
    )

    event_id = Column(
        String,
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=True
    )

    event = relationship(
        "Event",
        back_populates="notifications"
    )

    alert_id = Column(
        String,
        ForeignKey("alerts.id", ondelete="CASCADE"),
        nullable=True
    )

    alert = relationship(
        "Alert",
        back_populates="notifications"
    )